// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WORK.Context;

#nullable disable

namespace WORK.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230501123625_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WORK.Models.DATA_day", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("DATA_monthid")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("DATA_monthid");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("WORK.Models.DATA_event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("DATA_dayid")
                        .HasColumnType("integer");

                    b.Property<string>("categori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("DATA_dayid");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("WORK.Models.DATA_month", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("months");
                });

            modelBuilder.Entity("WORK.Models.DATA_day", b =>
                {
                    b.HasOne("WORK.Models.DATA_month", "DATA_month")
                        .WithMany("Days")
                        .HasForeignKey("DATA_monthid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DATA_month");
                });

            modelBuilder.Entity("WORK.Models.DATA_event", b =>
                {
                    b.HasOne("WORK.Models.DATA_day", "DATA_day")
                        .WithMany("Events")
                        .HasForeignKey("DATA_dayid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DATA_day");
                });

            modelBuilder.Entity("WORK.Models.DATA_day", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("WORK.Models.DATA_month", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
